// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNet_gram.Data;

namespace dotNet_gram.Migrations
{
    [DbContext(typeof(PostDbContext))]
    [Migration("20190214183002_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotNet_gram.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Caption = "This is awesome!",
                            Title = "awesome",
                            URL = "awesome.jpg",
                            Username = "Deziree T."
                        },
                        new
                        {
                            ID = 2,
                            Caption = "This is cool!",
                            Title = "cool",
                            URL = "cool.jpg",
                            Username = "Elisha C."
                        },
                        new
                        {
                            ID = 3,
                            Caption = "This is fun!",
                            Title = "fun",
                            URL = "fun.jpg",
                            Username = "Quinton R."
                        },
                        new
                        {
                            ID = 4,
                            Caption = "This is amazing!",
                            Title = "amazing",
                            URL = "amazing.jpg",
                            Username = "Zan J."
                        },
                        new
                        {
                            ID = 5,
                            Caption = "This is beautiful",
                            Title = "beautiful",
                            URL = "beautiful.jpg",
                            Username = "Lynette E."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
